"""init

Revision ID: 821890e7172f
Revises: 
Create Date: 2023-04-27 18:03:58.654744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821890e7172f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='eventstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('WAIT', 'WIN', 'LOSE', name='betstate'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
